import { SAMPLE_PROFILES } from "./github/samples";
import type { CardProfile } from "./dating/types";

// The "KEEP SWIPING" deck — real GitHub accounts baked once so the deck needs
// no per-view scout. The four showcase samples close the deck (the top card,
// seen first); these live-scouted profiles (captured 2026-08-09) fill out the
// stack so there's something to actually swipe through.

const BAKED: CardProfile[] = [
  {
    login: "akitaonrails",
    name: "Fabio Akita",
    avatarUrl: "https://avatars.githubusercontent.com/u/2840?s=480&u=6923ae49ba086f2c94d29287bc998bacf5b32010&v=4",
    location: "Brazil",
    repos: 119,
    age: 18,
    height: "5'11\"",
    match: 94,
    tier: "one",
    tierLabel: "THE ONE",
    verified: true,
    bio: [
      "My repos are famous. My DMs are not.",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "I've opened enough PRs to know how to make the first move.",
      "I speak 19 languages, fluently-ish.",
      "16 years on GitHub and still shipping — long-term material.",
      "Currently in my 'just one more commit' era.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Ruby", "Rust", "JavaScript", "Crystal"],
  },
  {
    login: "Kaori2",
    name: "kaori_katayama",
    avatarUrl: "https://avatars.githubusercontent.com/u/125297000?s=480&u=a7fe16affd7bbb97408573d2173cb6234b6eaca8&v=4",
    location: null,
    repos: 11,
    age: 3,
    height: "5'8\"",
    match: 61,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "TypeScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["TypeScript", "JavaScript", "HTML"],
  },
  {
    login: "fernandacaramico",
    name: "Fernanda Caramico",
    avatarUrl: "https://avatars.githubusercontent.com/u/46379117?s=480&u=d6f3b6bd96e1370c5365a35aeb8efa860f587943&v=4",
    location: "São Paulo",
    repos: 16,
    age: 7,
    height: "5'8\"",
    match: 84,
    tier: "turner",
    tierLabel: "HEAD-TURNER",
    verified: true,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "7 years on GitHub and still shipping — long-term material.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "HTML", "CSS"],
  },
  {
    login: "julialima1999",
    name: "Julia M. B. Lima",
    avatarUrl: "https://avatars.githubusercontent.com/u/61556770?s=480&u=232cb2f90352157a110eb82496a865d772aff61a&v=4",
    location: null,
    repos: 3,
    age: 6,
    height: "5'8\"",
    match: 66,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: true,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "Python"],
  },
  {
    login: "HenriquePiassi",
    name: "Henrique Piassi",
    avatarUrl: "https://avatars.githubusercontent.com/u/79462606?s=480&u=4ac28ea6d4697e14c503698cce357bdd4ad6d336&v=4",
    location: "Av. Brg. Faria Lima, 2055 - Pinheiros",
    repos: 2,
    age: 5,
    height: "5'8\"",
    match: 59,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "HTML is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["HTML"],
  },
  {
    login: "Wendel032",
    name: "Wendel032",
    avatarUrl: "https://avatars.githubusercontent.com/u/198674362?s=480&u=f15d88f8aa60b89db730aad06a8b76a36e6e3689&v=4",
    location: null,
    repos: 8,
    age: 1,
    height: "5'8\"",
    match: 54,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "HTML", "Dockerfile"],
  },
  {
    login: "VitorioBearari",
    name: "VitorioBearari",
    avatarUrl: "https://avatars.githubusercontent.com/u/199517203?s=480&u=ca21094432393973ce29d5c83bb9f4fbece2c22c&v=4",
    location: null,
    repos: 14,
    age: 1,
    height: "5'8\"",
    match: 57,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "Java is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Java", "Python", "HTML", "CSS"],
  },
  {
    login: "JhoelDiego2",
    name: "Jhoel Mita",
    avatarUrl: "https://avatars.githubusercontent.com/u/198672530?s=480&u=18c4010d253e2c2e12226a7d213208b986c23099&v=4",
    location: "São Paulo, SP",
    repos: 13,
    age: 1,
    height: "5'8\"",
    match: 69,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "I've opened enough PRs to know how to make the first move.",
      "I speak 8 languages, fluently-ish.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Python", "Java", "JavaScript", "Shell"],
  },
  {
    login: "Gabriel-Pereiraa",
    name: "Gabriel Pereira",
    avatarUrl: "https://avatars.githubusercontent.com/u/198849603?s=480&u=5be61acf84a2514ff184c2df114cfd03067afdf3&v=4",
    location: "São Paulo",
    repos: 8,
    age: 1,
    height: "5'8\"",
    match: 55,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "HTML"],
  },
  {
    login: "mcsscalabrin",
    name: "Matheus Scalabrin",
    avatarUrl: "https://avatars.githubusercontent.com/u/101526350?s=480&u=772dca276b8c893d320dc55e58efc28de365dd17&v=4",
    location: "São Paulo, Brazil",
    repos: 14,
    age: 4,
    height: "5'8\"",
    match: 65,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "Java is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Java", "JavaScript", "Shell", "HTML"],
  },
  {
    login: "OmarDahbur",
    name: "Omar Nidal",
    avatarUrl: "https://avatars.githubusercontent.com/u/198760082?s=480&u=ce6d117efc00fca7faed9053b599dc4ef6ebd387&v=4",
    location: "São Paulo - Brasil",
    repos: 11,
    age: 1,
    height: "5'8\"",
    match: 57,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "Java", "Python", "HTML"],
  },
  {
    login: "FelipeLima24",
    name: "Felipe Lima",
    avatarUrl: "https://avatars.githubusercontent.com/u/198760140?s=480&u=f4cbf223b52eb0f66e73d5cf44d77ca2ffa42d7d&v=4",
    location: "São Paulo",
    repos: 9,
    age: 1,
    height: "5'8\"",
    match: 55,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "Python", "HTML"],
  },
  {
    login: "JoaoVtC",
    name: "JoaoVtC",
    avatarUrl: "https://avatars.githubusercontent.com/u/198761425?s=480&u=a9412aabeb26b52a5ba1275c7232bc562f442e93&v=4",
    location: null,
    repos: 19,
    age: 1,
    height: "5'8\"",
    match: 60,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "I speak 7 languages, fluently-ish.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Java", "JavaScript", "C#", "Python"],
  },
  {
    login: "85ED",
    name: "Edson Felix",
    avatarUrl: "https://avatars.githubusercontent.com/u/160767641?s=480&u=d32b311f5c613600ef4cd6b5e0c30dca9bad6ca5&v=4",
    location: "São Paulo",
    repos: 43,
    age: 2,
    height: "5'8\"",
    match: 65,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "I speak 8 languages, fluently-ish.",
      "Currently in my 'just one more commit' era.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Java", "TypeScript", "C#", "Python"],
  },
  {
    login: "lorenzomeni",
    name: "Lorenzo Meni",
    avatarUrl: "https://avatars.githubusercontent.com/u/198671744?s=480&u=0febc76246f28e508c7747342b0ab1e381361eb3&v=4",
    location: null,
    repos: 10,
    age: 1,
    height: "5'8\"",
    match: 56,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "HTML is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["HTML"],
  },
  {
    login: "Beno-Goulart",
    name: "Beno Goulart",
    avatarUrl: "https://avatars.githubusercontent.com/u/135740382?s=480&u=a6278490be5558a5bd0c8e3d64ca361af653ff61&v=4",
    location: "São Paulo, SP - Brazil",
    repos: 29,
    age: 3,
    height: "5'8\"",
    match: 69,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "I speak 7 languages, fluently-ish.",
      "Currently in my 'just one more commit' era.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Java", "Python", "TypeScript", "JavaScript"],
  },
  {
    login: "LukasFah",
    name: "Lukas Farias",
    avatarUrl: "https://avatars.githubusercontent.com/u/199182791?s=480&u=dbefcec9b1a0c4c5e06509aec0e64845de5584e7&v=4",
    location: "São Paulo - SP",
    repos: 10,
    age: 1,
    height: "5'8\"",
    match: 55,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "Python is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Python", "HTML"],
  },
  {
    login: "Joao103001",
    name: "João Pedro França",
    avatarUrl: "https://avatars.githubusercontent.com/u/199535442?s=480&u=c7426dad5bdb33f0d0ea6314a03aa1c698569de3&v=4",
    location: null,
    repos: 10,
    age: 1,
    height: "5'8\"",
    match: 52,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "R", "HTML"],
  },
  {
    login: "Bryan-Anthony",
    name: "Bryan Anthony",
    avatarUrl: "https://avatars.githubusercontent.com/u/199614893?s=480&u=6f0cfa3692ad8e6c88ac9f02d3ff189a2b50497a&v=4",
    location: null,
    repos: 1,
    age: 1,
    height: "5'8\"",
    match: 53,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "HTML"],
  },
  {
    login: "brenokas",
    name: "Breno",
    avatarUrl: "https://avatars.githubusercontent.com/u/50001019?s=480&u=e547614054efcdfa47b8bb1949178704b296ba13&v=4",
    location: "São Paulo",
    repos: 29,
    age: 7,
    height: "5'8\"",
    match: 67,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "I speak 8 languages, fluently-ish.",
      "Currently in my 'just one more commit' era.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Java", "JavaScript", "Python", "Shell"],
  },
  {
    login: "RenanDaher1",
    name: "RenanDaher1",
    avatarUrl: "https://avatars.githubusercontent.com/u/199526561?s=480&u=f60904c5609a62cd2c8548d3c479db325366a2f9&v=4",
    location: null,
    repos: 7,
    age: 1,
    height: "5'8\"",
    match: 54,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "HTML"],
  },
  {
    login: "1camargo",
    name: "Gabriel Camargo",
    avatarUrl: "https://avatars.githubusercontent.com/u/65190073?s=480&u=65c9bb310a89cd4315aa1db3076e359e04c943e7&v=4",
    location: "Santo André, SP",
    repos: 25,
    age: 6,
    height: "5'8\"",
    match: 62,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "Java is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Java", "Python", "TypeScript", "HTML"],
  },
  {
    login: "pedrosakaue",
    name: "Pedro Guimarães Sakaue",
    avatarUrl: "https://avatars.githubusercontent.com/u/198657968?s=480&u=b380a844a8a9d51303e12ffe30d12ab1a7d6330d&v=4",
    location: null,
    repos: 10,
    age: 1,
    height: "5'8\"",
    match: 57,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "Python", "Java", "TypeScript"],
  },
  {
    login: "Vinicius-Melo-Rezende",
    name: "Vinicius-Melo-Rezende",
    avatarUrl: "https://avatars.githubusercontent.com/u/199091858?s=480&v=4",
    location: null,
    repos: 8,
    age: 1,
    height: "5'8\"",
    match: 53,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "Python is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Python", "HTML"],
  },
  {
    login: "davicaproni",
    name: "davicaproni",
    avatarUrl: "https://avatars.githubusercontent.com/u/198920242?s=480&u=10ba4c1d84a43e41736bc2d782bf61ac69cadfcb&v=4",
    location: null,
    repos: 13,
    age: 1,
    height: "5'8\"",
    match: 55,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "Python is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Python", "Shell", "TypeScript", "HTML"],
  },
  {
    login: "MarcioIoT",
    name: "Marcio",
    avatarUrl: "https://avatars.githubusercontent.com/u/47605125?s=480&u=8d0290d5c5464bac91fd662bfe847e91687800f4&v=4",
    location: "Paulista",
    repos: 12,
    age: 7,
    height: "5'8\"",
    match: 70,
    tier: "catch",
    tierLabel: "A CATCH",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "Shell is my love language.",
      "7 years on GitHub and still shipping — long-term material.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Shell", "TypeScript", "HTML"],
  },
  {
    login: "joaopedpaula",
    name: "João Pedro de Paula",
    avatarUrl: "https://avatars.githubusercontent.com/u/53584199?s=480&u=b62b972abd235f6659c9489b9111c6dfea85c3e1&v=4",
    location: null,
    repos: 8,
    age: 7,
    height: "5'8\"",
    match: 70,
    tier: "catch",
    tierLabel: "A CATCH",
    verified: true,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "JavaScript is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["JavaScript", "HTML", "CSS"],
  },
  {
    login: "manoelalmeida-io",
    name: "Manoel Almeida",
    avatarUrl: "https://avatars.githubusercontent.com/u/53584776?s=480&u=82530b4fcf82d77b5f94c03094b83512afb6d788&v=4",
    location: "São Paulo, SP - Brazil",
    repos: 93,
    age: 7,
    height: "5'8\"",
    match: 82,
    tier: "turner",
    tierLabel: "HEAD-TURNER",
    verified: true,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "I speak 10 languages, fluently-ish.",
      "7 years on GitHub and still shipping — long-term material.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["Java", "Kotlin", "JavaScript", "TypeScript"],
  },
  {
    login: "verriedu",
    name: "verriedu",
    avatarUrl: "https://avatars.githubusercontent.com/u/197656442?s=480&u=7e1f4f7a143f2dac11ac0e8df7093b19e9c65da2&v=4",
    location: null,
    repos: 2,
    age: 1,
    height: "5'8\"",
    match: 51,
    tier: "green",
    tierLabel: "GREEN FLAG",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "CSS is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["CSS"],
  },
  {
    login: "julia-araripe",
    name: "Júlia Araripe",
    avatarUrl: "https://avatars.githubusercontent.com/u/100041348?s=480&u=4e1265b854d2e6fd440e6acd489cd293f7a510eb&v=4",
    location: null,
    repos: 5,
    age: 4,
    height: "5'8\"",
    match: 62,
    tier: "keeper",
    tierLabel: "KEEPER",
    verified: false,
    bio: [
      "Not here for the stars. (Well. Maybe a few.)",
      "I commit. To the repo. And, reportedly, to the one who replies.",
      "HTML is my love language.",
      "Loves merge requests. Hates conflicts.",
    ],
    interests: ["HTML"],
  },
];

// The samples close the deck — the top card (queue[length-1]) is seen first,
// so a familiar face opens and the freshly scouted crowd follows.
export const SWIPE_PROFILES: CardProfile[] = [...BAKED, ...SAMPLE_PROFILES];

// Just the freshly scouted crowd — the ranking pool for the home "TOP
// PROFILES" strip (the showcase samples already get their own fan deck).
export const BAKED_PROFILES: CardProfile[] = BAKED;
